import { useState } from "react";
import { 
  AlertDialog, 
  AlertDialogAction, 
  AlertDialogCancel, 
  AlertDialogContent, 
  AlertDialogDescription, 
  AlertDialogFooter, 
  AlertDialogHeader, 
  AlertDialogTitle 
} from "@/components/ui/alert-dialog";
import { Checkbox } from "@/components/ui/checkbox";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { AlertTriangle, Shield, Users, RotateCcw } from "lucide-react";

interface CleanupConfirmationProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  repositoryName: string;
  commitCount: number;
  onConfirm?: () => void;
}

export function CleanupConfirmation({
  open,
  onOpenChange,
  repositoryName,
  commitCount,
  onConfirm
}: CleanupConfirmationProps) {
  const [backupConfirmed, setBackupConfirmed] = useState(false);
  const [teamNotified, setTeamNotified] = useState(false);
  const [consequencesUnderstood, setConsequencesUnderstood] = useState(false);

  const allChecked = backupConfirmed && teamNotified && consequencesUnderstood;

  const handleConfirm = () => {
    if (!allChecked) return;
    console.log('Cleanup confirmed for:', repositoryName);
    onConfirm?.();
    onOpenChange(false);
    // Reset checkboxes for next time
    setBackupConfirmed(false);
    setTeamNotified(false);
    setConsequencesUnderstood(false);
  };

  const handleCancel = () => {
    onOpenChange(false);
    // Reset checkboxes
    setBackupConfirmed(false);
    setTeamNotified(false);
    setConsequencesUnderstood(false);
  };

  return (
    <AlertDialog open={open} onOpenChange={onOpenChange}>
      <AlertDialogContent className="max-w-2xl" data-testid="dialog-cleanup-confirmation">
        <AlertDialogHeader>
          <AlertDialogTitle className="flex items-center gap-2 text-orange-600 dark:text-orange-400">
            <AlertTriangle className="h-5 w-5" />
            Confirm Commit Message Cleanup
          </AlertDialogTitle>
          <AlertDialogDescription className="text-base">
            You are about to clean up <Badge variant="outline">{commitCount} commit messages</Badge> in{" "}
            <span className="font-medium">{repositoryName}</span> by removing Replit auto-generated text.
          </AlertDialogDescription>
        </AlertDialogHeader>

        <div className="space-y-4">
          <div className="p-4 bg-blue-500/10 border border-blue-500/20 rounded-lg">
            <div className="flex items-center gap-3 mb-3">
              <div className="p-2 bg-blue-500/20 rounded-full">
                <span className="text-lg">🧹</span>
              </div>
              <div>
                <p className="font-semibold text-blue-400">Commit Message Cleanup</p>
                <p className="text-sm text-blue-300">Removing Replit auto-generated text from commit messages</p>
              </div>
            </div>
          </div>

          <div className="p-3 bg-orange-500/10 border border-orange-500/20 rounded-lg">
            <div className="text-sm space-y-2">
              <p className="font-semibold text-orange-400">What This Does:</p>
              <ul className="list-disc list-inside text-orange-300 space-y-1 ml-2 text-xs">
                <li>Keeps your original commit message and all code changes</li>
                <li>Removes Replit metadata like "Replit-Commit-Author", "Replit-Commit-Session-Id", etc.</li>
                <li>Removes "Replit Prompt: Auto-generated by Replit" text</li>
                <li>Creates new commits with cleaned messages and updates the branch</li>
                <li><strong>History rewriting means collaborators should pull the changes</strong></li>
              </ul>
              <p className="text-orange-300 text-xs mt-2 font-medium">Your code and commit content remain exactly the same - only messages are cleaned.</p>
            </div>
          </div>

          <div className="space-y-4">
            <h4 className="font-medium">Before proceeding, please confirm:</h4>
            
            <div className="space-y-3">
              <div className="flex items-start space-x-3">
                <Checkbox
                  id="backup-confirmed"
                  checked={backupConfirmed}
                  onCheckedChange={(checked) => setBackupConfirmed(checked === true)}
                  data-testid="checkbox-backup-confirmed"
                />
                <div className="grid gap-1.5 leading-none">
                  <label htmlFor="backup-confirmed" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer flex items-center gap-2">
                    <Shield className="h-4 w-4 text-muted-foreground" />
                    I have created a backup of this repository (optional but recommended)
                  </label>
                  <p className="text-xs text-muted-foreground">
                    Only commit messages are changed - your code remains the same
                  </p>
                </div>
              </div>

              <div className="flex items-start space-x-3">
                <Checkbox
                  id="team-notified"
                  checked={teamNotified}
                  onCheckedChange={(checked) => setTeamNotified(checked === true)}
                  data-testid="checkbox-team-notified"
                />
                <div className="grid gap-1.5 leading-none">
                  <label htmlFor="team-notified" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer flex items-center gap-2">
                    <Users className="h-4 w-4 text-muted-foreground" />
                    I have notified all team members about this operation
                  </label>
                  <p className="text-xs text-muted-foreground">
                    They must run <code className="bg-muted px-1 rounded text-xs">git reset --hard origin/main</code> or re-clone the repo
                  </p>
                </div>
              </div>

              <div className="flex items-start space-x-3">
                <Checkbox
                  id="consequences-understood"
                  checked={consequencesUnderstood}
                  onCheckedChange={(checked) => setConsequencesUnderstood(checked === true)}
                  data-testid="checkbox-consequences-understood"
                />
                <div className="grid gap-1.5 leading-none">
                  <label htmlFor="consequences-understood" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer flex items-center gap-2">
                    <RotateCcw className="h-4 w-4 text-muted-foreground" />
                    I understand this rewrites commit messages permanently
                  </label>
                  <p className="text-xs text-muted-foreground">
                    Commit messages will be cleaned and cannot be easily reverted
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <AlertDialogFooter>
          <AlertDialogCancel onClick={handleCancel} data-testid="button-cancel-cleanup">
            Cancel
          </AlertDialogCancel>
          <AlertDialogAction
            onClick={handleConfirm}
            disabled={!allChecked}
            className="bg-blue-600 text-white hover:bg-blue-700"
            data-testid="button-confirm-cleanup"
          >
            Clean Commit Messages
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}